apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}-server-headless-service
  namespace: {{ .Values.external.namespace }}
spec: 
  clusterIP: None
  selector:
    app: {{ .Values.server.name }}
