apiVersion: v1
kind: Service
metadata:
  name: arkouda-metrics-exporter
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "{{ .Values.metricsExporter.service.port }}"
    prometheus.io/scrape: "true"

spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsExporter.service.port }}
      targetPort: 5080
      protocol: TCP
  selector:
    app: arkouda-server
