---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.server.name }}-server-launch-script
  labels:
    name: {{ .Values.server.name }}-server-launch-script
data:
  script: |-

     #!/bin/bash
     sudo service ssh start

     set -x

     # Set env variables needed to start arkouda
     sudo sh -c "echo 'GASNET_MASTERIP=$MY_IP' >> /etc/environment"
     sudo sh -c "echo 'METRICS_SERVICE_NAME=$METRICS_SERVICE_NAME' >> /etc/environment"

     # Retrieve arkouda-locale pod IP addresses and set the corresponding env variable
     LOCALE_IPS="$(dig +search +short {{ .Values.locale.name }}-locale-ssh | tr '\n' ' ')"
     sudo sh -c "echo 'LOCALE_IPS=$LOCALE_IPS' >> /etc/environment"

     {{- if .Values.group.enabled }}
     GID={{ .Values.group.gid | int64 | quote }}
     GROUP={{ .Values.group.name }}
     {{- else }}
     GID=1000
     GROUP=ubuntu
     {{- end }}

     {{- if .Values.user.enabled }}
     UID={{ .Values.user.uid | int64 | quote }}
     USER={{ .Values.user.name }}
     {{- else }}
     UID=1000
     USER=ubuntu
     {{- end }}

     # Add user with home directory
     sudo useradd $USER -m -u $UID -g $GID
     sudo adduser $USER $USER
     HOME="/home/$USER"
     # Add group corresponding to gid and user
     sudo groupadd -g $GID $GROUP
     sudo groupadd $USER
     echo $USER

     # Add SSH certificate
     sudo -u $USER mkdir $HOME/.ssh
     sudo cp $HOME/ssh-keys/id_rsa* $HOME/.ssh/
     sudo chown -R $USER:$USER $HOME/.ssh
     chmod -R 600 $HOME/.ssh/*
     cat $HOME/.ssh/id_rsa.pub > $HOME/.ssh/authorized_keys

     # Generate list of arkouda-server and arkouda-locale IP addresses
     export SSH_SERVERS="$MY_IP $LOCALE_IPS" \

     # Start arkouda_server via the GASNET SSH_SPAWNER using the udp CHAPEL_COMM_SUBSTRATE and SSH_SERVER list of pod ip addresses
     {{- if .Values.server.metrics.collectMetrics }}
     /opt/arkouda/arkouda_server -nl ${NUMLOCALES:-1} --ServerDaemon.daemonTypes=ServerDaemonType.METRICS \
                                                      --memTrack=${MEMTRACK:-true} --authenticate=${AUTHENTICATE:-false} \
                                                      --logLevel=${LOG_LEVEL:-LogLevel.INFO} --memMax={{ .Values.server.memMax | int }}
     {{- else }}
     /opt/arkouda/arkouda_server -nl ${NUMLOCALES:-1} --memTrack=${MEMTRACK:-true} --authenticate=${AUTHENTICATE:-false} \
                                                      --logLevel=${LOG_LEVEL:-LogLevel.INFO} --memMax={{ .Values.server.memMax | int }}
     {{- end }}
     EOF
