apiVersion: v1
kind: Service
metadata:
  name: arkouda-metrics-exporter
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsExporter.service.port }}
      targetPort: {{ .Values.metricsExporter.service.port }}
      protocol: TCP
  selector:
    app: arkouda-server
