---

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.server.name }}-server-launch-script
  labels:
    name: {{ .Values.server.name }}-server-launch-script
data:
  script: |-

     #!/bin/bash
     service ssh start

     # Set user and group to run arkouda as
     {{- if .Values.user.enabled }}
     export USER={{ .Values.user.name }}
     export UID={{ .Values.user.uid | int64 }}
     {{- else }}
     export USER=ubuntu
     export UID=1000
     {{- end }}
     {{- if .Values.group.enabled }}
     export GROUP={{ .Values.group.name }}
     export GID={{ .Values.group.gid | int64 }}
     {{- else }}
     export GROUP=ubuntu
     export GID=1000
     {{- end }}
     # Create group corresponding to gid and user
     groupadd -g $GID $GROUP
     groupadd $USER
     # Add user with home directory and user group
     useradd $USER -m -u $UID -g $GID
     adduser $USER $USER
     # Add SSH certificate
     mkdir /home/$USER/.ssh
     cp /home/ubuntu/ssh-keys/id_rsa* /home/$USER/.ssh/
     chmod 600 /home/$USER/.ssh/*
     cat /home/$USER/.ssh/id_rsa.pub > /home/$USER/.ssh/authorized_keys
     chown -R $USER:$USER /home/$USER/.ssh

     # Set env variables needed to start arkouda
     echo 'GASNET_MASTERIP=$MY_IP' >> /etc/environment
     echo 'METRICS_SERVICE_NAME=$METRICS_SERVICE_NAME' >> /etc/environment

     # Retrieve arkouda-locale pod IP addresses and set the corresponding env variable
     LOCALE_IPS="$(dig +search +short {{ .Values.locale.name }}-locale-ssh | tr '\n' ' ')"
     echo 'LOCALE_IPS=$LOCALE_IPS' >> /etc/environment

     # Start arkouda_server as the configured user
     sudo -u $USER bash <<EOF

     # Generate list of arkouda-server and arkouda-locale IP addresses
     export SSH_SERVERS="$MY_IP $LOCALE_IPS" \

     # Start arkouda_server via the GASNET SSH_SPAWNER using the udp CHAPEL_COMM_SUBSTRATE and SSH_SERVER list of pod ip addresses
     {{- if .Values.server.metrics.collectMetrics }}
     /opt/arkouda/arkouda_server -nl ${NUMLOCALES:-1} --ServerDaemon.daemonTypes=ServerDaemonType.METRICS \
                                                      --memTrack=${MEMTRACK:-true} --authenticate=${AUTHENTICATE:-false} \
                                                      --logLevel=${LOG_LEVEL:-LogLevel.INFO} --memMax={{ .Values.server.memMax | int }}
     {{- else }}
     /opt/arkouda/arkouda_server -nl ${NUMLOCALES:-1} --memTrack=${MEMTRACK:-true} --authenticate=${AUTHENTICATE:-false} \
                                                      --logLevel=${LOG_LEVEL:-LogLevel.INFO} --memMax={{ .Values.server.memMax | int }}
     {{- end }}
     EOF
