apiVersion: v1
kind: Service
metadata:
  name: arkouda-metrics-exporter
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "5080"
    prometheus.io/scrape: "true"

spec:
  type: ClusterIP
  ports:
    - port: 5080
      protocol: TCP
  selector:
    app: arkouda-server
