kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arkouda-pod-reader
subjects:
- kind: User
  name: {{ .Values.user }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: arkouda-pod-reader
  apiGroup: rbac.authorization.k8s.io
