kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.server.name }}-service
subjects:
- kind: User
  name: {{ .Values.user.name }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .Values.server.name }}-service
  apiGroup: rbac.authorization.k8s.io

