kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.server.name }}-service
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount }}
roleRef:
  kind: Role
  name: {{ .Values.server.name }}-service
  apiGroup: rbac.authorization.k8s.io

