apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.locale.appName}}-locale-ssh
spec:
  type: ClusterIP
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
  selector:
    app: {{ .Values.locale.appName }}
