kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.locale.name }}-locale-launch-script
  labels:
    name: {{ .Values.locale.name }}-locale-launch-script
data:
  script: |-

     #!/bin/bash
     sudo service ssh start

     {{- if .Values.group.enabled }}
     GID={{ .Values.group.gid | int64 | quote }}
     GROUP={{ .Values.group.name }}
     {{- else }}
     GID=1000
     GROUP=ubuntu
     {{- end }}

     {{- if .Values.user.enabled }}
     UID={{ .Values.user.uid | int64 | quote }}
     USER={{ .Values.user.name }}
     {{- else }}
     UID=1000
     USER=ubuntu
     {{- end }}

     sudo groupadd -g $GID $GROUP
     sudo useradd $USER -m -u $UID -g $GID
     sudo adduser $USER $USER
     HOME="/home/$USER"
     sudo groupadd $USER
     echo $USER

     sudo chown -R $USER:$USER /opt

     # Add SSH certificate
     sudo mkdir $HOME/.ssh
     sudo cp $HOME/ssh-keys/id_rsa* $HOME/.ssh/
     sudo chown -R $USER:$USER $HOME/.ssh

     chmod -R 600 $HOME/.ssh/*
     cat $HOME/.ssh/id_rsa.pub > $HOME/.ssh/authorized_keys

     /bin/bash -c -- "while true; do sleep 600; done;"
