apiVersion: v1
kind: ServiceAccount
metadata:
  name: arkouda-workflows-service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arkouda-workflows
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
        - monitoring.coreos.com
    resources:
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - jobs
      - pods
      - roles
      - rolebindings
      - services
      - servicemonitors
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arkouda-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arkouda-workflows
subjects:
- kind: ServiceAccount
  name: arkouda-workflows-service-account
