apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: delete-prometheus-arkouda-exporter-
spec:
  entrypoint: delete-prometheus-arkouda-exporter
  serviceAccountName: arkouda-workflows-service-account
  podGC:
    strategy: OnWorkflowSuccess
  workflowTemplateRef:
    name: delete-prometheus-arkouda-exporter