apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: delete-arkouda-on-kubernetes-
spec:
  entrypoint: delete-arkouda-on-kubernetes
  serviceAccountName: arkouda-workflows-service-account
  podGC:
    strategy: OnWorkflowSuccess
  workflowTemplateRef:
    name: delete-arkouda-on-kubernetes