apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deploy-prometheus-arkouda-exporter-
spec:
  entrypoint: launch-prometheus-arkouda-exporter
  serviceAccountName: arkouda-workflows-service-account
  podGC:
    strategy: OnWorkflowSuccess
  workflowTemplateRef:
    name: deploy-prometheus-arkouda-exporter