apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deploy-arkouda-on-kubernetes-
spec:
  entrypoint: deploy-arkouda-on-kubernetes
  serviceAccountName: arkouda-workflows-service-account
  podGC:
    strategy: OnWorkflowSuccess
  workflowTemplateRef:
    name: deploy-arkouda-on-kubernetes