apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.exporter.service.name }} 
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.exporter.service.port }}
      targetPort: 5080
      protocol: TCP
  selector:
    app: {{ .Values.exporter.server.appName }}

