apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.exporter.service.name }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "{{ .Values.exporter.service.port }}"
    prometheus.io/scrape: "true" 
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.exporter.service.port }}
      targetPort: 5080
      protocol: TCP
  selector:
    app: {{ .Values.exporter.server.appName }}

