apiVersion: v1
kind: Secret
metadata:
  name: arkouda-sa
  annotations:
    kubernetes.io/service-account.name: arkouda-sa # matches the ServiceAccount name defined in previous step
type: kubernetes.io/service-account-token
