# values for arkouda-udp-server chart.

######################## Pod Settings ########################

releaseVersion: # bearsrus arkouda-udp-server image version
imagePullPolicy: Always

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 2048Mi

################ Arkouda Server Configuration ################

server: 
  numLocales: # total number of Arkouda locales = number of arkouda-udp-locale pods + 1
  authenticate: false # whether to require token authentication
  verbose: false # enable verbose logging
  memTrack: true # enable memory tracking (required for memMax and metrics export)
  memMax: 1000000000 # maximum bytes of RAM to be used per locale
  threadsPerLocale: # number of cpu cores to be used per locale
  logLevel: LogLevel.DEBUG # logging level
  name: # name of server
  service:
    type: ClusterIP
    port: 5555 # Arkouda k8s service port
    name: # k8s service name for Arkouda server
  metrics:
    collectMetrics: # indicates whether to collect metrics, defaults to false
    service:
      name: # service name for Arkouda metrics service endpoint
      port: 5556

locale:
  name: # arkouda-udp-locale app name used to find locale IP addresses
  podMethod: GET_POD_IPS 

external:
  k8sHost: # Kubernetes API url used to register service(s)
  namespace: # namespace Arkouda will register service

persistence:
  enabled: # indicates whether files can be written to/read from the host system, defaults to false
  containerPath: /arkouda-files # container directory for reading/writing Arkouda files
  hostPath: # host directory for reading/writing Arkouda files

metricsExporter:
  name: # Kubernetes app and server name for prometheus-arkouda-exporter
  releaseVersion: # bearsrus prometheus-arkouda-exporter image version
  imagePullPolicy: IfNotPresent
  pollingIntervalSeconds: 10 # polling interval prometheus-arkouda-exporter willl pull metrics from Arkouda
  serviceMonitor: 
    enabled: # indicates if ServiceMonitor registration is to be used, defaults to true
    pollingInterval: 15s
    additionalLabels:
      launcher: kubernetes # labels that enable Prometheus to discover Arkouda ServiceMonitor
    targetLabels:
      - arkouda_instance
      - launcher

user:
  enabled: # indicates whether to run Arkouda as a specified user, defaults to false
  name: # name of user running arkouda and CN for corresponding secret for rolebindings
  uid: # uid of user running Arkouda

group:
  enabled: # indicates whether to run Arkouda as a specified user with corresponding group, defaults to false
  name: # name of group user needs to configured for to execute host commands
  gid: # gid of group user needs to configured for to execute host commands

serviceaccount: # name of Arkouda ServiceAccount used for binding Arkouda k8s roles

secrets:
  ssh: # name of ssh secret used to launch Arkouda locales
  sa: # name of service-account-token assigned to the Arkouda ServiceAccount
