# Default values for arkouda-server-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

######################## Pod Settings ########################

imageRepository: bearsrus
releaseVersion: v2023.03.01
imagePullPolicy: IfNotPresent

################ Arkouda Server Configuration ################

server: 
  numLocales: # total number of Arkouda locales = number of arkouda-udp-locale pods + 1
  authenticate: # whether to require token authentication
  verbose: # enable verbose logging
  memTrack: true
  threadsPerLocale: # number of cpu cores to be used per locale
  memMax: # maximum bytes of RAM to be used per locale
  logLevel: LogLevel.INFO
  service:
    type: # k8s service type, usually ClusterIP, NodePort, or LoadBalancer
    port: # service port Arkouda is listening on, defaults to 5555
    targetPort: # if service tyoe is ClusterIP or LoadBalancer, defaults to 5555
    nodeport: # if service type is Nodeport
    name: # service name
  metrics:
    collectMetrics: # whether to collect metrics and make them available via  k8s service
    service:
      name: # k8s service name for the Arkouda metrics service endpoint
      port: # k8s service port for the Arkouda metrics service endpoint, defaults to 5556
      targetPort: # k8s targetPort mapping to the Arkouda metrics port, defaults to 5556
locale:
  appName: arkouda-locale
  podMethod: GET_POD_IPS
external:
  persistence:
    enabled: false
    path: /opt/locale # pod directory path DO NOT CHANGE
    hostPath: # host machine path
  certFile: /etc/ssl/arkouda/tls.crt
  keyFile: /etc/ssl/arkouda/tls.key
  k8sHost: 
  namespace: # namespace Arkouda will register service
  service: 
    name: # k8s service name Arkouda will register
    port: # k8s service port Arkouda will register, defaults to 5555
    targetPort: # k8s service targetPort Arkouda will register, defaults to 5555
metricsExporter:
  imageRepository: bearsrus
  releaseVersion: # prometheus-arkouda-exporter release version
  imagePullPolicy: IfNotPresent
  service:
    name: # prometheus-arkouda-exporter service name
    port: # prometheus-arkouda-exporter service port, defaults to 5080
  pollingIntervalSeconds: 5
  dynamicScrapeTarget: true
